Support App Route & Pages Router
aralroca/next-translate-plugin pull request #22
Opened 2023-05-17 15:21 UTC by alvesvin

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
The webpack loader selects the correct helpers on a page by page basis rather than `experimental.appDir` config.

**Which issue (if any) does this pull request address?**
#21 

**Is there anything you'd like reviewers to focus on?**
Perhaps readability and size

2023-05-17 15:21 UTC, alvesvin commented
Just a notice, this is incomplete yet. I'm going to be working on in later today.

2023-05-17 16:01 UTC, aralroca commented on src/loader.ts
> +    if (page.endsWith('page.tsx')) {
Here we need to take into account all the possible formats (.tsx, .js, .md, etc...)

2023-05-17 16:12 UTC, aralroca requested changes
Thanks for your contribution. Keep waiting for the final changes

2023-05-18 04:12 UTC, alvesvin commented
Some updates:

- We should support translation in error, loading and layout components (for Next 13)

- Next 12 router implements sub-path i18n automatically while translating that to the `lang` search params at the page level. That's not true for the new Next 13 router. In this regard I think we should follow the [pattern provided in the documentation](https://nextjs.org/docs/app/building-your-application/routing/internationalization) where the user must define a dynamic route to handle sub-path i18n and, after that, we start using the `lang` param from the dynamic route rather than the search param for the App Router.

### Sub-path routing

Providing more context, in Next 12, when defining i18n options in `next.config.js` it is possible to navigate to the following routes:

`/about` loads the default language
`/en/about` loads the `en` version of the page
`/br/about` loads the `br` version of the page

For Next 13, users would need to create `/app/[lang]/about/page.tsx` (same for any other internationalized page). Together with that, users need to create a `middleware.ts` to redirect to the correct language sub-path. Then we would use page's `props.params.lang` rather than `props.searchParams.lang` for App Router pages.

### Domain routing

I think domain routing should be possible to define inside `middleware.ts`.

2023-05-18 12:59 UTC, aralroca commented on __tests__/loader.test.js
> +describe('nextTranslate', () => {
❤️

2023-05-18 15:10 UTC, alvesvin commented
Added a todo list at the top to keep track of the progress 🎉

2023-05-19 05:23 UTC, alvesvin commented
The idea with `determineResourceType` function is to use it to return a string like `APP_ROUTER_SERVER_PAGE`, `APP_ROUTER_SERVER_LAYOUT`, etc, to represent the resource type and based on that we do a switch to add necessary helpers accordinly. Is that ok? I'm afraid to go too far and uselessly rewrite too much.

I'm doing this as first step to support translation in layout, error & loading pages.

2023-05-20 03:46 UTC, alvesvin commented
I'm kinda stuck with a weird behavior in layout/loading/error components.

Inside a server layout component the `useTranslation` hook seems to sometimes [get a stale value from the last render](https://imgur.com/CTn0nf5) and other times it seems to [get stuck with one value](https://imgur.com/Nuv7HRx).

Funny part is that server pages work correctly even though they are being treated exactly the same by the loader (perhaps that's the problem).

I'm going to be full focused on this PR all day tomorrow. Looking forward to finish it.

2023-05-22 10:55 UTC, aralroca commented
@alvesvin Thank you for all your efforts. I have seen that there is currently a bug for hooks/helpers that have the "use client", reported here: https://github.com/aralroca/next-translate-plugin/issues/23 

since you are with this complex task could you try to fix this case? otherwise I will try to fix it once your PR is merged. Thanks! 🙏

2023-05-22 11:54 UTC, alvesvin commented
> @alvesvin Thank you for all your efforts. I have seen that there is currently a bug for hooks/helpers that have the "use client", reported here: #23
> 
> since you are with this complex task could you try to fix this case? otherwise I will try to fix it once your PR is merged. Thanks! pray

Oh, okay. I will fix it.

2023-05-24 11:33 UTC, alvesvin commented
Guys, sorry for the delay. I have only a limited time to work on this PR. This feature is trickier than it looked like, but I'm working on it as much as I can.

I've tried a few things but still haven't come up with a reliable implementation for i18n in layouts, loading & error.

2023-05-24 14:07 UTC, aralroca commented
@alvesvin Don't be afraid to make several PR, I think it would be easier to review.  Feels free to remove the part of layout, loading, error and add it in another PR.

2023-05-27 00:04 UTC, alvesvin commented
Hey, @aralroca I'm sorry to say that I think I'm not going to be able to accomplish this PR :disappointed:. Since I use this library in production, I was hoping to try and fix it as it's currently not compatible with Next 13 features. Problem is I think I'm not doing a good job. The last commits is an implementation that feels kinda hacky, bloated and bug-prone. I've tried a few things but I don't have the rationale why the code is the way it is today and what should be done to productively improve it or what should be rethought.

I think I started it wrong, maybe not asking the right questions. If you could shed some light on what you think the solution would be, I'm still willing to implement it.

Sorry to make you all wait for nothing :cactus:

2023-05-31 12:50 UTC, aralroca commented
@alvesvin Don't worry, your contribution has already been important. As soon as I have some time I will try to implement it and I will take into account all your work on this PR. Thank you very much for your contribution 😊

2023-05-31 22:13 UTC, AndresDevelop commented
Brilliant work  on this one folks.  I was wondering if you have a sort of deadline for the next release. This issues is time sensitive for my project . thank you 🎖️

2023-06-05 21:54 UTC, aralroca commented
@AndresDevelop @alvesvin Try next-translate-plugin  [2.3.0-canary.1](https://github.com/aralroca/next-translate-plugin/releases/tag/2.3.0-canary.1) prerelease please 🙏

2023-06-06 13:33 UTC, aralroca commented
> Hey @aralroca
> 
> Using the canary version gives me this error:
> 
> * error ./node_modules/next/dist/compiled/@next/react-refresh-utils/dist/runtime.js

mmmmh! Which version of Next.js are you using?

2023-06-06 13:36 UTC, izoukhai commented
> > Hey @aralroca
> > Using the canary version gives me this error:
> > 
> > * error ./node_modules/next/dist/compiled/@next/react-refresh-utils/dist/runtime.js
> 
> mmmmh! Which version of Next.js are you using @izoukhai?

Next 13.4.4, along with next-translate 2.0.6.

Forgot to mention that I had no pages/ directory, creating one fixed that issue but raised a new one:

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /Users/izoukhai/test/node_modules/react-dom/package.json`

2023-06-06 13:39 UTC, izoukhai commented
Well, after completely restarting the project, it seems to work. However, certain translations get loaded and replaced by their keys quickly after, giving a bunch of error tied to server/client mismatch. I will investigate the issue, might be related to my implementation as it impacts only my navbar

2023-06-06 13:42 UTC, izoukhai commented
@aralroca the issue seems to impact client components only.

2023-06-06 18:19 UTC, aralroca commented
New prerelease https://github.com/aralroca/next-translate-plugin/releases/tag/2.3.0-canary.2

2023-06-06 22:02 UTC, izoukhai commented
> New prerelease https://github.com/aralroca/next-translate-plugin/releases/tag/2.3.0-canary.2

The issue with pages folder is gone, but client components still don't load translations

2023-06-07 08:21 UTC, aralroca commented
Thanks for your feedback @izoukhai. I'm going to investigate the client components what change in the last versions of Next.js.

2023-06-07 09:07 UTC, aralroca commented
@izoukhai is possible to create a repo that reproduces this issue to help me to fix it? Thanks!

2023-06-07 14:45 UTC, izoukhai commented
> @izoukhai is possible to create a repo that reproduces this issue to help me to fix it? Thanks!

Yup I will give you the repo in a minute!

2023-06-07 14:56 UTC, izoukhai commented
@aralroca here you go: https://github.com/izoukhai/next-translate-example-repo

2023-06-07 14:57 UTC, aralroca commented
Thanks @izoukhai

2023-06-08 18:33 UTC, aralroca commented
@izoukhai thanks for sharing, should be fixed in `2.3.0-canary.3` (next-translate + next-translate-plugin in `2.3.0-canary.3` version)

2023-06-18 17:35 UTC, aralroca commented
Done in 2.3

2023-06-18 17:35 UTC, closed without merging

2023-06-19 19:37 UTC, aralroca commented
@alvesvin @izoukhai Layouts are supported in `2.4.0-canary.1` (next-translate + next-translate-plugin in the same version). Would be great if you can try and give me some feedback before the next release. Thanks 🙏